workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $HOME/Library/Developer/Xcode/DerivedData/*
        - $HOME/.gradle/caches/*
    triggering:
      events:
        - push
        - pull_request
      branch:
        include_patterns:
          - main
          - develop
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/flutter" > android/local.properties
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
